apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: dns-tools
spec:
  manifest:
    version: 1
    install:
      dnsmasq:
        pkg-path: dnsmasq
      dig:
        pkg-path: dig
    include:
      environments:
        - dir: /var/lib/git/nxmatic/fleet/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
    options:
      systems:
        - aarch64-darwin
        - aarch64-linux
        - x86_64-linux
        - x86_64-darwin
  env:
    name: asciidoc
    version: 1
