apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: dns-tools
spec:
  manifest:
    version: 1
    install:
      dnsmasq:
        pkg-path: dnsmasq
      dig:
        pkg-path: dig
    profile:
      common: |
        export ANTORA_CACHE_DIR="${FLOX_ENV_PROJECT}/.cache/antora"
        export DOCS_BUILD_DIR="${FLOX_ENV_PROJECT}/.output/docs"
        : "${KROKI_SERVER_URL:=https://kroki.io}"
        export KROKI_SERVER_URL
        mkdir -p "${ANTORA_CACHE_DIR}" "${DOCS_BUILD_DIR}"
        if [ -x "${FLOX_ENV_PROJECT}/node_modules/.bin/antora" ]; then
          export PATH="${FLOX_ENV_PROJECT}/node_modules/.bin:${PATH}"
        fi
    include:
      environments:
        - dir: /var/lib/git/nxmatic/fleet/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
    options:
      systems:
        - aarch64-darwin
        - aarch64-linux
        - x86_64-linux
        - x86_64-darwin
  env:
    name: asciidoc
    version: 1
